title: Sebastian Algharaballi-Yanow
show_downloads: False
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  style: compressed
extras:
  - <script src="/assets/js/script.js"></script>
markdown: kramdown
kramdown:
  parse_block_html: true
