title: Hello! My name is Sebastian.
#logo: relative path image
#description: text below image
show_downloads: False
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  style: compressed
extras:
  - <script src="/assets/js/script.js"></script>
